WebSiteBanHang/Controllers/PhanQuyenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanHang.Models;

namespace WebSiteBanHang.Controllers
{
    [Authorize(Roles = "QuanTri")]
    public class PhanQuyenController : Controller
    {
        
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        // GET: PhanQuyen
        public ActionResult Index()
        {
            return View(db.LoaiThanhViens.Where(n => n.UuDai == 1).OrderByDescending(n => n.MaLoaiTV));
        }

        [HttpGet]
        public ActionResult PhanQuyen(int? id)
        {
            //Lấy MaLoaiTV cần chỉnh sửa dựa vào id
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            LoaiThanhVien ltv = db.LoaiThanhViens.SingleOrDefault(n => n.MaLoaiTV == id);
            if (ltv == null)
            {
                return HttpNotFound();
            }
            //Lay ra ds quyen (de load ra checkbox)
            ViewBag.MaQuyen = db.Quyens;
            //lay ra ds quyen cua loai thanh vien
            ViewBag.LoaiTVQuyen = db.LoaiThanhVien_Quyen.Where(n => n.MaLoaiTV == id && n.Quyen.TrangThai == true);
            return View(ltv);
        }

        [HttpPost]
        public ActionResult PhanQuyen(int? MaLTV, IEnumerable<LoaiThanhVien_Quyen> lstPhanQuyen)
        {
            //TH1: Neu da tien hanh phan quyen nhung muon phan quyen lai
            //B1: Xoa nhung quyen cua thuoc loai TV do
            var lstDaPhanQuyen = db.LoaiThanhVien_Quyen.Where(n => n.MaLoaiTV == MaLTV);
            if (lstDaPhanQuyen!= null)
            {
                db.LoaiThanhVien_Quyen.RemoveRange(lstDaPhanQuyen);
                db.SaveChanges();
            }

            //Ktra list danh sach quyen duoc check
            foreach (var item in lstPhanQuyen)
            {
                if (item.MaQuyen != null)
                {
                    //neu duoc check thi insert du lieu vao bang pahn quyen
                    db.LoaiThanhVien_Quyen.Add(item);
                }
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult ThemMember()
        {

            return View();
        }

        [HttpPost]
        public ActionResult ThemMember(LoaiThanhVien loaiTV)
        {
            if (ModelState.IsValid)
            {
                db.LoaiThanhViens.Add(loaiTV);
                loaiTV.UuDai = 1;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult XoaMember(int? id)
        {
            //Lấy quyền cần chỉnh sửa dựa vào id
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            LoaiThanhVien q = db.LoaiThanhViens.SingleOrDefault(n => n.MaLoaiTV == id);
            if (q == null)
            {
                return HttpNotFound();
            }

            return View(q);
        }

        [HttpPost]
        public ActionResult XoaMember(LoaiThanhVien model)
        {

            db.Entry(model).State = System.Data.Entity.EntityState.Modified;
            model.UuDai = 0;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

WebSiteBanHang/Views/PhanQuyen/Index.cshtml
@using WebSiteBanHang.Models;
@model IEnumerable<LoaiThanhVien>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<table class="table">
    <tr>
        <td>Mã Loại TV</td>
        <td>Loại TV</td>
        <td>Tác Vụ</td>

    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>@item.MaLoaiTV</td>
    <td>@item.TenLoai</td>

    <td class="btn btn-success">
        @Html.ActionLink("Phân Quyền", "PhanQuyen", new { id = item.MaLoaiTV })
    </td>

</tr>
    }
</table>

WebSiteBanHang/Views/PhanQuyen/PhanQuyen.cshtml
@using WebSiteBanHang.Models;
@model LoaiThanhVien

@{
    ViewBag.Title = "PhanQuyen";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h1>PhanQuyen</h1>
<h2 style="color:red;">Loại Thành Viên: <font color="orange">@Model.TenLoai</font></h2>

@{ 
    //lấy danh sách quyền
    IEnumerable<Quyen> lstQuyen = (IEnumerable<Quyen>)ViewBag.MaQuyen;
    IEnumerable<LoaiThanhVien_Quyen> lstLTVQuyen = (IEnumerable<LoaiThanhVien_Quyen>)ViewBag.LoaiTVQuyen;
}


@using (Html.BeginForm())
{
    //mã loại TV
    @Html.Hidden("MaLTV",Model.MaLoaiTV)
    if (lstLTVQuyen != null)
    {
        //Đối với thành viên đã phân quyền rồi
        for (int j=0; j<lstQuyen.Count();j++)
        {
            int k = 0; // tạo biến k làm biến đếm để duyệt vòng lặp của bảng quyền xem nếu mà
                       //loại thành viên nào có mã quyền (LoaiTV_Quyen) ứng với quyền (MaQuyen)
            for (int i=0; i<lstLTVQuyen.Count(); i++)
            {
                if (lstQuyen.ElementAt(j).MaQuyen == lstLTVQuyen.ElementAt(i).MaQuyen)
                {
                    k++;
                    break;
                }
            }
            if (k!= 0)
            {
                <div class="col-md-4" style="font-size:15pt;">
                    <input type="hidden" value="@Model.MaLoaiTV" name="@Url.Content("["+j+"].MaLoaiTV")" />
                    <input checked="checked" style="width: 20px; height:20px;" type="checkbox" name="@Url.Content("["+j+"].MaQuyen")" value="@lstQuyen.ElementAt(j).MaQuyen" /> @lstQuyen.ElementAt(j).TenQuyen
                </div>
            }
            else
            {
                <div class="col-md-4" style="font-size:15pt;">
                    <input type="hidden" value="@Model.MaLoaiTV" name="@Url.Content("["+j+"].MaLoaiTV")" />
                    <input  style="width: 20px; height:20px;" type="checkbox" name="@Url.Content("["+j+"].MaQuyen")" value="@lstQuyen.ElementAt(j).MaQuyen" /> @lstQuyen.ElementAt(j).TenQuyen
                </div>
            }
            k = 0;
        }
    }
    else
    {
        //Doi vơi thành viên đã phân quyền rồi
        for (int i=0; i<lstQuyen.Count(); i++)
        {
            //Lay ds quyền
            <div class="col-md-4" style="font-size:15pt;">
                    <input type="hidden" value="@Model.MaLoaiTV" name="@Url.Content("["+i+"].MaLoaiTV")" />
                    <input  style="width: 20px; height:20px;" type="checkbox" name="@Url.Content("["+i+"].MaQuyen")" value="@lstQuyen.ElementAt(i).MaQuyen" /> @lstQuyen.ElementAt(i).TenQuyen
            </div>
        }
    }
    <div class="clearfix"></div>
    <input type="submit" value="Thực hiện" class="btn btn-success" />
}
<br />
@Html.ActionLink("Trở về","Index",null, new {@class="btn btn-primary" })

WebSiteBanHang/Views/PhanQuyen/ThemMember.cshtml
@model WebSiteBanHang.Models.LoaiThanhVien

@{
    ViewBag.Title = "ThemMember";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}


@using (Html.BeginForm(Html.BeginForm("ThemMember", "PhanQuyen", FormMethod.Post, new { @enctype = "multipart/form-data" }))) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Thêm Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.TenLoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenLoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

WebSiteBanHang/Views/PhanQuyen/XoaMember.cshtml
@model WebSiteBanHang.Models.LoaiThanhVien

@{
    ViewBag.Title = "ThemMember";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}


@using (Html.BeginForm(Html.BeginForm("XoaMember", "PhanQuyen", FormMethod.Post, new { @enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thêm Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <h2>Xác nhận xóa?</h2>
        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiTV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaLoaiTV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaLoaiTV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenLoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenLoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Xóa" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>